CREATE DATABASE jdbc_test;
use jdbc_test;
CREATE TABLE Client (
	ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(15) NOT NULL,
    PHONE VARCHAR(9) NOT NULL,
    AGE INT NOT NULL,
    PRIMARY KEY(ID)
);